//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ES.Repository.BaseRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaseStatu
    {
        public CaseStatu()
        {
            this.PrisonerCaseInfoes = new HashSet<PrisonerCaseInfo>();
        }
    
        public int CaseStatusId { get; set; }
        public string CaseStatusName { get; set; }
        public string CaseStatusDescription { get; set; }
    
        public virtual ICollection<PrisonerCaseInfo> PrisonerCaseInfoes { get; set; }
    }
}
